### fetch a client
GET http://localhost:8282/lab/client/1

### fetch clients
GET http://localhost:8282/lab/client

### get current user id
GET http://localhost:8282/lab/session/currentUserId

### fetch a client (Docker)
GET http://localhost:8283/lab/client/1
Accept-Encoding: gzip
