### fetch a client
GET http://localhost:8282/lab/client/1

### fetch clients
GET http://localhost:8282/lab/client

### fetch a player
GET http://localhost:8282/lab/player/1

### fetch a player by resource_id
GET http://localhost:8282/lab/player/resource/abcd1234

### fetch players
GET http://localhost:8282/lab/player

### fetch a client (Docker)
GET http://localhost:8283/lab/client/1
Accept-Encoding: gzip
