### ping
GET http://localhost:8282/ping

### create a player
POST http://localhost:8282/lab/player
Content-Type: application/json

{
  "resource_id": "my-resource-id",
  "name": "Jono",
  "description": "some or other description"
}

### delete a player
DELETE http://localhost:8282/lab/player/3
If-Match: W/"0"

### fetch a player
GET http://localhost:8282/lab/player/1

### fetch a player by resource_id
GET http://localhost:8282/lab/player/resource/abcd1234

### player checkin by id
PUT http://localhost:8282/lab/player/checkin/1
If-Match: W/"0"

### fetch players
GET http://localhost:8282/lab/player

### get current user id
GET http://localhost:8282/lab/session/currentUserId

### fetch a client (Docker)
GET http://localhost:8080/lab/client/1
Accept-Encoding: gzip

### ping (docker)
GET http://localhost:8080/ping
